from enum import StrEnum


class CapabilityStatus(StrEnum):
    CONDITIONAL = "CONDITIONAL"
    SUPPORTED = "SUPPORTED"
    UNKNOWN = "UNKNOWN"
    UNSUPPORTED = "UNSUPPORTED"


class CapabilityType(StrEnum):
    ATOMIC_SETTLEMENT = "ATOMIC_SETTLEMENT"
    COLLATERAL = "COLLATERAL"
    CONVERSION = "CONVERSION"
    CROSS_BORDER = "CROSS_BORDER"
    DELIVERY_VERSUS_PAYMENT = "DELIVERY_VERSUS_PAYMENT"
    DVP = "DVP"
    ESCROW = "ESCROW"
    INTRADAY_LIQUIDITY = "INTRADAY_LIQUIDITY"
    PAYMENT = "PAYMENT"
    PAYMENT_VERSUS_PAYMENT = "PAYMENT_VERSUS_PAYMENT"
    PROGRAMMABLE_TRANSFER = "PROGRAMMABLE_TRANSFER"
    PVP = "PVP"
    REDEMPTION = "REDEMPTION"
    SETTLEMENT = "SETTLEMENT"
    TRANSFER = "TRANSFER"
    TREASURY = "TREASURY"


class EquivalenceStatus(StrEnum):
    CONDITIONALLY_EQUIVALENT = "CONDITIONALLY_EQUIVALENT"
    FUNCTIONALLY_EQUIVALENT = "FUNCTIONALLY_EQUIVALENT"
    NOMINALLY_EQUIVALENT = "NOMINALLY_EQUIVALENT"
    NOT_EQUIVALENT = "NOT_EQUIVALENT"
    SETTLEMENT_EQUIVALENT = "SETTLEMENT_EQUIVALENT"
    UNKNOWN = "UNKNOWN"


class MoneyState(StrEnum):
    AVAILABLE = "AVAILABLE"
    CONVERTING = "CONVERTING"
    ENCUMBERED = "ENCUMBERED"
    FAILED = "FAILED"
    FINAL = "FINAL"
    FROZEN = "FROZEN"
    ISSUED = "ISSUED"
    LOCKED = "LOCKED"
    REDEEMING = "REDEEMING"
    RESERVED = "RESERVED"
    SETTLING = "SETTLING"
    TRANSFERRING = "TRANSFERRING"
    UNKNOWN = "UNKNOWN"


class MoneyEventType(StrEnum):
    CONVERSION_EXECUTED = "CONVERSION_EXECUTED"
    CONVERSION_REQUESTED = "CONVERSION_REQUESTED"
    ENCUMBERED = "ENCUMBERED"
    FROZEN = "FROZEN"
    ISSUED = "ISSUED"
    LOCKED = "LOCKED"
    MINTED = "MINTED"
    REDEEMED = "REDEEMED"
    REDEMPTION_REQUESTED = "REDEMPTION_REQUESTED"
    RELEASED = "RELEASED"
    RESERVED = "RESERVED"
    SETTLEMENT_FAILED = "SETTLEMENT_FAILED"
    SETTLEMENT_FINAL = "SETTLEMENT_FINAL"
    SETTLEMENT_STARTED = "SETTLEMENT_STARTED"
    TRANSFER_REQUESTED = "TRANSFER_REQUESTED"
    TRANSFERRED = "TRANSFERRED"
    UNFROZEN = "UNFROZEN"
    UNLOCKED = "UNLOCKED"


class RelationType(StrEnum):
    BACKED_BY = "BACKED_BY"
    BRIDGED_TO = "BRIDGED_TO"
    COLLATERALIZABLE_AGAINST = "COLLATERALIZABLE_AGAINST"
    CONVERTIBLE_TO = "CONVERTIBLE_TO"
    EXCHANGEABLE_FOR = "EXCHANGEABLE_FOR"
    MINTED_FROM = "MINTED_FROM"
    REDEEMABLE_FOR = "REDEEMABLE_FOR"
    SETTLEABLE_AGAINST = "SETTLEABLE_AGAINST"
    SETTLED_IN = "SETTLED_IN"
    TRANSFERABLE_TO = "TRANSFERABLE_TO"


class TransitionEvaluationStatus(StrEnum):
    COMPATIBLE = "COMPATIBLE"
    CONDITIONALLY_COMPATIBLE = "CONDITIONALLY_COMPATIBLE"
    CONDITIONAL = "CONDITIONAL"
    INCOMPATIBLE = "INCOMPATIBLE"
    UNKNOWN = "UNKNOWN"


class RequirementPriority(StrEnum):
    MANDATORY = "MANDATORY"
    PREFERRED = "PREFERRED"
    OPTIONAL = "OPTIONAL"


class RequirementOperator(StrEnum):
    AVAILABLE_DURING = "AVAILABLE_DURING"
    EQUALS = "EQUALS"
    FORBIDS = "FORBIDS"
    GREATER_THAN = "GREATER_THAN"
    GREATER_THAN_OR_EQUAL = "GREATER_THAN_OR_EQUAL"
    IN = "IN"
    LESS_THAN = "LESS_THAN"
    LESS_THAN_OR_EQUAL = "LESS_THAN_OR_EQUAL"
    NOT = "NOT"
    NOT_EQUALS = "NOT_EQUALS"
    NOT_IN = "NOT_IN"
    REQUIRES = "REQUIRES"
    WITHIN = "WITHIN"


class RequirementComposition(StrEnum):
    AND = "AND"
    OR = "OR"
    NOT = "NOT"


class EvidenceStatus(StrEnum):
    CONFLICTING = "CONFLICTING"
    MISSING = "MISSING"
    STALE = "STALE"
    UNVERIFIED = "UNVERIFIED"
    VALID = "VALID"


class ProfileLifecycleStatus(StrEnum):
    DRAFT = "DRAFT"
    PUBLISHED = "PUBLISHED"
    REVOKED = "REVOKED"
    SUPERSEDED = "SUPERSEDED"
    UNKNOWN = "UNKNOWN"


class ParticipantType(StrEnum):
    BANK = "BANK"
    CORPORATE = "CORPORATE"
    CUSTODIAN = "CUSTODIAN"
    INFRASTRUCTURE_PROVIDER = "INFRASTRUCTURE_PROVIDER"
    ISSUER = "ISSUER"
    OTHER = "OTHER"
    PAYMENT_PROVIDER = "PAYMENT_PROVIDER"
    SETTLEMENT_AGENT = "SETTLEMENT_AGENT"
    VENUE = "VENUE"


class NetworkType(StrEnum):
    CENTRALIZED = "CENTRALIZED"
    HYBRID = "HYBRID"
    OTHER = "OTHER"
    PERMISSIONED_DLT = "PERMISSIONED_DLT"
    PUBLIC_DLT = "PUBLIC_DLT"


class MappingClassification(StrEnum):
    APPROXIMATED = "APPROXIMATED"
    DERIVED = "DERIVED"
    EXACT = "EXACT"
    LOSSLESS = "LOSSLESS"
    LOSSY = "LOSSY"
    UNSUPPORTED = "UNSUPPORTED"


class MappingDirection(StrEnum):
    BIDIRECTIONAL = "BIDIRECTIONAL"
    EXTERNAL_TO_OMST = "EXTERNAL_TO_OMST"
    OMST_TO_EXTERNAL = "OMST_TO_EXTERNAL"


class SettlementRouteType(StrEnum):
    FALLBACK = "FALLBACK"
    PRIMARY = "PRIMARY"
    RECOVERY = "RECOVERY"


class ReasonSeverity(StrEnum):
    BLOCKING = "BLOCKING"
    INFORMATIONAL = "INFORMATIONAL"
    WARNING = "WARNING"


class CompatibilityReasonCode(StrEnum):
    ACCESS_RESTRICTED = "ACCESS_RESTRICTED"
    ATOMICITY_UNAVAILABLE = "ATOMICITY_UNAVAILABLE"
    AVAILABILITY_MISMATCH = "AVAILABILITY_MISMATCH"
    CAPABILITY_MISSING = "CAPABILITY_MISSING"
    CONFLICTING_EVIDENCE = "CONFLICTING_EVIDENCE"
    CURRENCY_MISMATCH = "CURRENCY_MISMATCH"
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"
    EVIDENCE_STALE = "EVIDENCE_STALE"
    FINALITY_MISMATCH = "FINALITY_MISMATCH"
    JURISDICTION_CONSTRAINT = "JURISDICTION_CONSTRAINT"
    LATENCY_REQUIREMENT_UNMET = "LATENCY_REQUIREMENT_UNMET"
    LIQUIDITY_EVIDENCE_STALE = "LIQUIDITY_EVIDENCE_STALE"
    LIQUIDITY_INSUFFICIENT = "LIQUIDITY_INSUFFICIENT"
    REDEMPTION_CONSTRAINT = "REDEMPTION_CONSTRAINT"
    SETTLEMENT_WINDOW_MISMATCH = "SETTLEMENT_WINDOW_MISMATCH"
    STATE_INCOMPATIBLE = "STATE_INCOMPATIBLE"
    TRANSFERABILITY_RESTRICTED = "TRANSFERABILITY_RESTRICTED"
    UNKNOWN_REQUIREMENT = "UNKNOWN_REQUIREMENT"


class SettlementLegType(StrEnum):
    ASSET = "ASSET"
    CASH = "CASH"
    COLLATERAL = "COLLATERAL"
    FEE = "FEE"
    FX = "FX"


class SettlementLegRelation(StrEnum):
    ATOMIC = "ATOMIC"
    CONDITIONAL = "CONDITIONAL"
    DEPENDENT = "DEPENDENT"
    NETTED = "NETTED"
    SEQUENTIAL = "SEQUENTIAL"


class SettlementBundleMode(StrEnum):
    ATOMIC = "ATOMIC"
    CONDITIONAL_ATOMIC = "CONDITIONAL_ATOMIC"
    NETTED = "NETTED"
    NON_ATOMIC = "NON_ATOMIC"
    PARTIALLY_ATOMIC = "PARTIALLY_ATOMIC"
    SEQUENCED = "SEQUENCED"
    UNKNOWN = "UNKNOWN"


class TransitionType(StrEnum):
    CONVERT = "CONVERT"
    ENCUMBER = "ENCUMBER"
    FREEZE = "FREEZE"
    LOCK = "LOCK"
    MINT = "MINT"
    REDEEM = "REDEEM"
    RELEASE = "RELEASE"
    RELEASE_ENCUMBRANCE = "RELEASE_ENCUMBRANCE"
    RESERVE = "RESERVE"
    SETTLE = "SETTLE"
    SWAP = "SWAP"
    TRANSFER = "TRANSFER"
    UNFREEZE = "UNFREEZE"
    UNLOCK = "UNLOCK"


class LifecycleState(StrEnum):
    AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
    AUTHORIZED = "AUTHORIZED"
    FINAL = "FINAL"
    INITIATED = "INITIATED"
    IN_TRANSITION = "IN_TRANSITION"
    LIQUIDITY_FAILED = "LIQUIDITY_FAILED"
    REQUESTED = "REQUESTED"
    REVERTED = "REVERTED"
    SETTLEMENT_FAILED = "SETTLEMENT_FAILED"
    SETTLING = "SETTLING"
    TIMEOUT = "TIMEOUT"
    UNKNOWN = "UNKNOWN"
    VALIDATED = "VALIDATED"
    VALIDATION_FAILED = "VALIDATION_FAILED"


class IntegrityStatus(StrEnum):
    DEGRADED = "DEGRADED"
    IMPROVED = "IMPROVED"
    INCOMPARABLE = "INCOMPARABLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    PRESERVED = "PRESERVED"
    UNKNOWN = "UNKNOWN"


class EvidenceSourceType(StrEnum):
    community = "community"
    derived = "derived"
    issuer_declared = "issuer_declared"
    observed = "observed"
    official = "official"
    simulated = "simulated"
    unknown = "unknown"
