from enum import StrEnum


class CapabilityStatus(StrEnum):
    CONDITIONAL = "CONDITIONAL"
    SUPPORTED = "SUPPORTED"
    UNKNOWN = "UNKNOWN"
    UNSUPPORTED = "UNSUPPORTED"


class CapabilityType(StrEnum):
    ATOMIC_SETTLEMENT = "ATOMIC_SETTLEMENT"
    COLLATERAL = "COLLATERAL"
    CONVERSION = "CONVERSION"
    CROSS_BORDER = "CROSS_BORDER"
    DELIVERY_VERSUS_PAYMENT = "DELIVERY_VERSUS_PAYMENT"
    ESCROW = "ESCROW"
    INTRADAY_LIQUIDITY = "INTRADAY_LIQUIDITY"
    PAYMENT = "PAYMENT"
    PAYMENT_VERSUS_PAYMENT = "PAYMENT_VERSUS_PAYMENT"
    PROGRAMMABLE_TRANSFER = "PROGRAMMABLE_TRANSFER"
    REDEMPTION = "REDEMPTION"
    SETTLEMENT = "SETTLEMENT"
    TRANSFER = "TRANSFER"
    TREASURY = "TREASURY"


class EquivalenceStatus(StrEnum):
    CONDITIONALLY_EQUIVALENT = "CONDITIONALLY_EQUIVALENT"
    FUNCTIONALLY_EQUIVALENT = "FUNCTIONALLY_EQUIVALENT"
    NOMINALLY_EQUIVALENT = "NOMINALLY_EQUIVALENT"
    NOT_EQUIVALENT = "NOT_EQUIVALENT"
    SETTLEMENT_EQUIVALENT = "SETTLEMENT_EQUIVALENT"
    UNKNOWN = "UNKNOWN"


class MoneyState(StrEnum):
    AVAILABLE = "AVAILABLE"
    CONVERTING = "CONVERTING"
    ENCUMBERED = "ENCUMBERED"
    FAILED = "FAILED"
    FINAL = "FINAL"
    FROZEN = "FROZEN"
    ISSUED = "ISSUED"
    LOCKED = "LOCKED"
    REDEEMING = "REDEEMING"
    RESERVED = "RESERVED"
    SETTLING = "SETTLING"
    TRANSFERRING = "TRANSFERRING"
    UNKNOWN = "UNKNOWN"


class MoneyEventType(StrEnum):
    CONVERSION_EXECUTED = "CONVERSION_EXECUTED"
    CONVERSION_REQUESTED = "CONVERSION_REQUESTED"
    ENCUMBERED = "ENCUMBERED"
    FROZEN = "FROZEN"
    ISSUED = "ISSUED"
    LOCKED = "LOCKED"
    MINTED = "MINTED"
    REDEEMED = "REDEEMED"
    REDEMPTION_REQUESTED = "REDEMPTION_REQUESTED"
    RELEASED = "RELEASED"
    RESERVED = "RESERVED"
    SETTLEMENT_FAILED = "SETTLEMENT_FAILED"
    SETTLEMENT_FINAL = "SETTLEMENT_FINAL"
    SETTLEMENT_STARTED = "SETTLEMENT_STARTED"
    TRANSFER_REQUESTED = "TRANSFER_REQUESTED"
    TRANSFERRED = "TRANSFERRED"
    UNFROZEN = "UNFROZEN"
    UNLOCKED = "UNLOCKED"


class RelationType(StrEnum):
    BACKED_BY = "BACKED_BY"
    BRIDGED_TO = "BRIDGED_TO"
    COLLATERALIZABLE_AGAINST = "COLLATERALIZABLE_AGAINST"
    CONVERTIBLE_TO = "CONVERTIBLE_TO"
    EXCHANGEABLE_FOR = "EXCHANGEABLE_FOR"
    MINTED_FROM = "MINTED_FROM"
    REDEEMABLE_FOR = "REDEEMABLE_FOR"
    SETTLEABLE_AGAINST = "SETTLEABLE_AGAINST"
    SETTLED_IN = "SETTLED_IN"


class TransitionEvaluationStatus(StrEnum):
    COMPATIBLE = "COMPATIBLE"
    CONDITIONAL = "CONDITIONAL"
    INCOMPATIBLE = "INCOMPATIBLE"
    UNKNOWN = "UNKNOWN"


class TransitionType(StrEnum):
    CONVERT = "CONVERT"
    ENCUMBER = "ENCUMBER"
    FREEZE = "FREEZE"
    LOCK = "LOCK"
    MINT = "MINT"
    REDEEM = "REDEEM"
    RELEASE = "RELEASE"
    RELEASE_ENCUMBRANCE = "RELEASE_ENCUMBRANCE"
    RESERVE = "RESERVE"
    SETTLE = "SETTLE"
    SWAP = "SWAP"
    TRANSFER = "TRANSFER"
    UNFREEZE = "UNFREEZE"
    UNLOCK = "UNLOCK"


class LifecycleState(StrEnum):
    AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"
    AUTHORIZED = "AUTHORIZED"
    FINAL = "FINAL"
    INITIATED = "INITIATED"
    IN_TRANSITION = "IN_TRANSITION"
    LIQUIDITY_FAILED = "LIQUIDITY_FAILED"
    REQUESTED = "REQUESTED"
    REVERTED = "REVERTED"
    SETTLEMENT_FAILED = "SETTLEMENT_FAILED"
    SETTLING = "SETTLING"
    TIMEOUT = "TIMEOUT"
    UNKNOWN = "UNKNOWN"
    VALIDATED = "VALIDATED"
    VALIDATION_FAILED = "VALIDATION_FAILED"


class IntegrityStatus(StrEnum):
    DEGRADED = "DEGRADED"
    IMPROVED = "IMPROVED"
    INCOMPARABLE = "INCOMPARABLE"
    NOT_APPLICABLE = "NOT_APPLICABLE"
    PRESERVED = "PRESERVED"
    UNKNOWN = "UNKNOWN"


class EvidenceSourceType(StrEnum):
    community = "community"
    derived = "derived"
    issuer_declared = "issuer_declared"
    observed = "observed"
    official = "official"
    simulated = "simulated"
    unknown = "unknown"
