from enum import StrEnum


class MoneyState(StrEnum):
    ISSUED = "ISSUED"; AVAILABLE = "AVAILABLE"; RESERVED = "RESERVED"; LOCKED = "LOCKED"
    TRANSFERRING = "TRANSFERRING"; SETTLING = "SETTLING"; FINAL = "FINAL"; REDEEMING = "REDEEMING"
    CONVERTING = "CONVERTING"; ENCUMBERED = "ENCUMBERED"; FROZEN = "FROZEN"; FAILED = "FAILED"; UNKNOWN = "UNKNOWN"

class TransitionType(StrEnum):
    TRANSFER = "TRANSFER"; RESERVE = "RESERVE"; RELEASE = "RELEASE"; LOCK = "LOCK"; UNLOCK = "UNLOCK"
    REDEEM = "REDEEM"; MINT = "MINT"; CONVERT = "CONVERT"; SWAP = "SWAP"; SETTLE = "SETTLE"
    ENCUMBER = "ENCUMBER"; RELEASE_ENCUMBRANCE = "RELEASE_ENCUMBRANCE"; FREEZE = "FREEZE"; UNFREEZE = "UNFREEZE"

class LifecycleState(StrEnum):
    REQUESTED = "REQUESTED"; VALIDATED = "VALIDATED"; AUTHORIZED = "AUTHORIZED"; INITIATED = "INITIATED"
    IN_TRANSITION = "IN_TRANSITION"; SETTLING = "SETTLING"; FINAL = "FINAL"; VALIDATION_FAILED = "VALIDATION_FAILED"
    AUTHORIZATION_FAILED = "AUTHORIZATION_FAILED"; LIQUIDITY_FAILED = "LIQUIDITY_FAILED"; TIMEOUT = "TIMEOUT"
    SETTLEMENT_FAILED = "SETTLEMENT_FAILED"; REVERTED = "REVERTED"; UNKNOWN = "UNKNOWN"

class IntegrityStatus(StrEnum):
    PRESERVED = "PRESERVED"; DEGRADED = "DEGRADED"; IMPROVED = "IMPROVED"; INCOMPARABLE = "INCOMPARABLE"; UNKNOWN = "UNKNOWN"

class EvidenceSourceType(StrEnum):
    official = "official"; issuer_declared = "issuer_declared"; observed = "observed"; derived = "derived"
    simulated = "simulated"; community = "community"; unknown = "unknown"
